[SERVER]
host = 127.0.0.1
port = 8000
endpoint = /api/v1/alerts

[AGENT]
node_ip = 192.168.1.105
monitoring_interval_seconds = 4
dataset_path = ../data/raw/KDDTest+.txt
features_path = ../data/processed/selected_features.json
